const captainImage = require("./images/members/ananya.jpg");
const memberImages = {
    'aaran': require("./images/members/aaran.jpg"),
    'ananya': require("./images/members/ananya.jpg"),
    'anshul': require("./images/members/anshul.jpg"),
    'bar': require("./images/members/bar.jpg"),
    'colson': require("./images/members/colson.jpg"),
    'connor_block': require("./images/members/connor_block.jpg"),
    'connor_floyd': require("./images/members/connor_floyd.jpg"),
    'daen': require("./images/members/daen.jpg"),
    'deepak': require("./images/members/deepak.jpg"),
    'defaultpic': require("./images/members/defaultpic.jpg"),
    'elian': require("./images/members/elian.jpg"),
    'emilio': require("./images/members/emilio.jpg"),
    'ethan': require("./images/members/ethan.jpg"),
    'henry_hui': require("./images/members/henry_hui.jpg"),
    'henry_wong': require("./images/members/henry_wong.jpg"),
    'idara': require("./images/members/idara.jpg"),
    'kimathra': require("./images/members/kimathra.jpg"),
    'lynn': require("./images/members/lynn.jpeg"),
    'lyra': require("./images/members/lyra.jpeg"),
    'marcelo': require("./images/members/marcelo.jpg"),
    'matthew': require("./images/members/matthew.jpg"),
    'nathan': require("./images/members/nathan.jpg"),
    'niharika': require("./images/members/niharika.jpg"),
    'oliver': require("./images/members/oliver.jpg"),
    'omar': require("./images/members/omar.jpg"),
    'peter': require("./images/members/peter.jpg"),
    'raymond_chen': require("./images/members/raymond_chen.jpg"),
    'raymond_shen': require("./images/members/raymond_shen.jpg"),
    'rexton': require("./images/members/rexton.jpg"),
    'senal': require("./images/members/senal.jpg"),
    'shawn': require("./images/members/shawn.jpg"),
    'thomas': require("./images/members/thomas.jpg"),
    'tristan': require("./images/members/tristan.jpg"),
    'zaid': require("./images/members/zaid.jpg"),
};

export { captainImage, memberImages };
